import { Typography } from "@mui/material";
import styles from "../../styles/Entries.module.css";
import { useNavigate } from "react-router-dom";

const Camp = () => {

    const navigate = useNavigate();

    return (
        <div className={styles.text}>
            <div className={styles.title}>
                Camp
                <hr />
            </div>
            <div className={styles.container}>
                <div className={styles.date}>
                    August 26, 2022
                </div>
                <div className={styles.link} onClick={() => { navigate("/blog") }}>
                    See all posts
                </div>
            </div>
            <div className={styles.body}>
                <Typography variant="body1">
                    <p>&ldquo;Pass me another rock,&rdquo; said Tim as he watched the one he had just thrown skip across the still morning water.&nbsp;</p>
                    <p>The sun had risen only a couple hours ago but was already emitting an unwavering radiance characteristic of a hot summer&rsquo;s day. Tim and his friend Mark felt its intense heat on their skin, but were almost completely unperturbed by its obstinate efforts to raise their body temperatures. The sun&rsquo;s attacks were mostly thwarted by the cool water they were wading in and the pleasant breeze that gently coerced their hair into a variable state of disorder. Mark tossed another rock towards the waiting hand of his friend a few feet in front of him. Soon Tim sent it skipping after its companion, its gradually shortening steps marked by circular ripples that slowly faded into the calm of the lake.</p>
                    <p>Tim walked back towards the shoreline and sat on the sand beside his friend. &ldquo;What are we doing today?&rdquo; he asked.&nbsp;</p>
                    <p>This was not the first time this question had been asked of Mark. In fact, it had been posed with a rigid regularity each day since they had arrived at camp&hellip; a week ago? &nbsp;After a few moments&rsquo; thought, Mark realized he couldn&rsquo;t remember how long they had been there. He found it very hard to organize events on the island into discrete days. It was as though they were stored in his memory in a haphazard clutter irrespective of time.</p>
                    <p>&ldquo;What about the North Island?&rdquo; said Tim after realizing that Mark wasn&rsquo;t going to respond. &ldquo;We haven&rsquo;t been there since like two summers ago when we went camping with your dad&rdquo;.&nbsp;</p>
                    <p>&ldquo;Yeah for good reason. It&rsquo;s just a bunch of trees up there and dad says there could be bears. Besides, there are no camps on that side of the island, so nobody really goes over there anyway.&rdquo;</p>
                    <p>&ldquo;Exactly. We could be the first to fully explore North Island. Maybe we could even find something to tell my brother about.&rdquo;&nbsp;</p>
                    <p>&nbsp; &nbsp;&nbsp;Mark contemplated this argument for a moment. Impressing Tim&rsquo;s brother by mapping a new part of the island wasn&rsquo;t nearly as attractive to him as it seemed to be to his friend. Notwithstanding, he felt a strange sense of obligation to match the enthusiasm Tim was showing at the prospect of this adventure. Before he knew what he was doing, he felt his hands on the hot sand pushing himself up onto his feet. He felt the muscles in his face being pulled upwards as if by invisible strings into a grin that mirrored his friend&rsquo;s. Without any more deliberation, the boys began their march north.</p>
                    <p><br /></p>
                    <p style={{ textAlign: "center" }}>#</p>
                    <p>&ldquo;I want you to tell me something you&rsquo;ve never told me before&rdquo; said Tim as he swerved to avoid a muddy patch on the trail.</p>
                    <p>&nbsp; &nbsp;&nbsp;&ldquo;I&rsquo;ve known you for almost my entire life Tim, what could I possibly have to tell you about at this point?&rdquo;</p>
                    <p>&nbsp; &nbsp;&nbsp;&ldquo;Well, there&rsquo;s got to be&nbsp;something&nbsp;I don&rsquo;t know about you, doesn&rsquo;t there? Tell me some sort of secret. It doesn&rsquo;t have to be really special, but I always like to hear new secrets&rdquo;.</p>
                    <p>Mark internally rolled his eyes in exasperation. Tim is generally not one to engage in idle conversation. He always likes to be learning something new either about the world or the person with whom he is conversing. He particularly likes to learn secret things because he feels a sense of empowerment after having learned something that is generally not known. Upon hearing a secret, Tim invariably reaffirms his trustworthiness by solemnly declaring that the secret is safe with him. And, in fact, Mark had no doubt that anything he told him would remain completely confidential. There was very little he refused to divulge to his friend, the primary struggle was usually finding something new to tell him.</p>
                    <p>&ldquo;Well, did I ever tell you about that time I stole Jenny&rsquo;s pen?&rdquo;</p>
                    <p>&ldquo;Yeah you did!&rdquo; laughed Tim. &ldquo;She didn&rsquo;t even notice right? Didn&rsquo;t you have to steal like three of them before she figured it out?&rdquo;</p>
                    <p>&ldquo;Four actually.&rdquo;</p>
                    <p>&ldquo;Four! That was so funny. She was asking everyone except you what happened to her pens! Why&rsquo;d you steal them though anyway?&rdquo;</p>
                    <p>&ldquo;I don&rsquo;t know,&rdquo; said Mark. &ldquo;Sometimes I just like to test things, you know? I wanted to see how easy it would be to take them. And then I wanted to see how long I could do it before she&rsquo;d figure it out. I still have her pens though, for when she asks for them.&rdquo;&nbsp;</p>
                    <p>&ldquo;I&rsquo;m not some kind of thief,&rdquo; Mark assured his friend. &ldquo;I&rsquo;ve never&nbsp;actually&nbsp;stolen anything. I always give people their stuff back if they ask for it.&rdquo;</p>
                    <p>Tim thought about this for a while and just as he appeared ready to respond, the boys saw the sign they had been looking for. &ldquo;NORTH ILAND&rdquo; was etched in wavy letters on a wooden board hammered to the tree in front of them. Beyond this point there seemed to be a precipitous end to the path they had hitherto been following, almost as if all those that had walked it before had turned around at exactly the same point. The boys both noticed this but were undeterred. They&rsquo;d been to North Island before with Mark&rsquo;s father and were altogether confident in their ability to navigate it. They continued on past the sign and into the deeper woods.</p>
                    <p>The boys felt some sort of change in the air as they crossed the boundary between North and South. It was an inexplicable discomfort, like they were somewhere decidedly different from the place they had been just seconds earlier. As they continued further away from the familiarity of the path, it became increasingly difficult for them to continue; as though they were attached to rubber bands that stretched further with every step they took.&nbsp;</p>
                    <p>Just as Mark was about to suggest they go somewhere else, the boys heard a sort of shrill screech followed by a bang that appeared to be coming from every direction at once. &ldquo;Heard&rdquo; is an accurate descriptor only insofar as it correctly identifies the ears as the entry point of the sound to their bodies. After the noise passed through their ears, it quickly morphed into something much more profound than just a compression of air particles around their heads. It became a feeling that ramified through their entire bodies, engaging all the nerves it came across. Mark began to smell something burning and moments later he heard the crackling of a material exposed to intense heat. He looked around frantically but was unable to find the source of the sound. Feeling dizzy, he bent down and put his hands on the leafy forest floor to steady himself. Despite their appearance, the leaves felt hard and rough, capable of scraping the hands that had naively trusted them a moment earlier.&nbsp;</p>
                    <p>&ldquo;What was that?&rdquo; exclaimed Mark. &ldquo;Did you feel that?&rdquo;. &nbsp;Mark made a move to run back towards the safety of the path but stopped when he realized that his friend had not reacted to his words. Tim was still crouched on the ground with his eyes closed, seemingly unaware of the fact that he was being spoken to. &ldquo;Tim! Can you hear me? Are you okay?&rdquo;</p>
                    <p>Mark rushed back to his friend and bent down in front of him. He clapped his hands in front of the boy&rsquo;s face trying to free him from the trance he appeared to be in. &ldquo;Wake up Tim! C&rsquo;mon please wake up!&rdquo;</p>
                    <p>Mark shook the motionless boy, but Tim refused to give any indication that he was cognisant of his friend&rsquo;s pleading. Mark wanted to run and get help but his feet felt planted to the ground. It was as though he was merely spectating the situation unfolding before him from a place far removed from the forest. He felt as though he could only bang on the walls of his mind and make futile attempts to free himself of the restraints that tied him to the ground.</p>
                    <p>He embraced Tim in a hug. He sobbed on his shoulder imploring him to wake up. Just as he was beginning to lose hope, he felt the motionless body he was gripping go rigid. It was like a shock had gone through Tim&rsquo;s body coercing all the muscles it passed into contracting simultaneously. Mark moved back just as the boy&rsquo;s eyes shot open.&nbsp;</p>
                    <p>&ldquo;Oh thank God!&rdquo; cried Mark. &ldquo;That wasn&rsquo;t funny! You really scared me there for a second. What happened? Are you okay?&rdquo;</p>
                    <p>Tim didn&rsquo;t react to the words of his friend. Even his eyes seemed not to change. They didn&rsquo;t move across Mark&rsquo;s face to better examine the tears now drying on his cheeks, they didn&rsquo;t soften to reflect any sympathy for the boy trembling with worry in front of them. Instead, they remained focused on the range of trees ahead of him just as they had been before the sound. It was there they stayed as Tim jumped up and began a sort of march in the direction his head was pointed.</p>
                    <p>Mark fell back on the ground, startled by the sudden movement. For the first time in his life he was afraid of his friend. He felt the icy cold hand of fear grip his heart, immobilizing his limbs. He wanted to run as fast as he could away from this situation and away from Tim, but he couldn&rsquo;t lift himself off the ground.&nbsp;</p>
                    <p>It was at this moment that Tim&rsquo;s head slowly turned towards him. It was only after his head was fully rotated that Tim&rsquo;s eyes began to move. They calmly shifted downwards until they locked on the petrified boy silently sobbing on the forest floor. It was as though Tim simultaneously saw Mark in great depth and looked right through him. An observer might say that he was&nbsp;evaluating&nbsp;Mark. If this was what he was doing, he did it with the calm confidence of a predator assessing its injured prey before finally ending its suffering. Moments later, Tim&rsquo;s head turned back to its original position in a deliberate, methodical way as if his neck was filled with gears and cogs instead of biological muscles. Then he began to walk.</p>
                    <p>Mark managed to summon his voice from the deep well it had been cast into for time enough to call his friend&rsquo;s name one last time. Unperturbed, Tim remained in a phantasmagoric trance calmly placing one foot in front of the other in a steadfast march to some unseen destination.</p>
                    <p>Despite the deep sense of dread Mark felt circulating through his veins, he somehow managed to rise and begin cautiously following Tim. As their march continued, he began to notice Tim was beginning to look less&nbsp;clean. At first, the changes were subtle like a seemingly new spot of dirt on his shirt, or a little rip in his shorts &ndash; things that one&rsquo;s mind could comfortably convince itself were there previously but overlooked. Then Mark noticed a stream of blood meandering out of the maw of a particularly vicious rip in Tim&rsquo;s shirt. He watched as a clump of hair detached itself from Tim&rsquo;s head and floated to the ground with incongruous grace.&nbsp;</p>
                    <p>As they moved deeper into the heart of the North Forest, the sun began to lose its battle with the tall trees as they prevented more and more of its light from reaching the forest floor. Mark averted his gaze from the canopy and turned back to look at his friend. Where there had been clothes, there were now only rags, skin that had once been fair and full of life was now shredded and bruised, legs once strong and healthy were now crooked and unwieldy.&nbsp;</p>
                    <p>Suddenly, Tim stopped his steady march. He turned to Mark and smiled, showing an irregular pattern of empty spaces in place of the white crowns that had been there previously. Then he ran at Mark. He ran at him like a tiger charging a baby deer, his face contorted into a soundless laugh. With a scream, Mark turned and charged into the forest. He bolted past trees and bushes ignoring their attacks on his arms and legs. As he ran, the sound of his feet on the leaves began to resemble the crunch of glass.&nbsp;</p>
                    <p>Just when he felt that he could go no further, Mark saw a little clearing in the distance out of the corner of his eye. Perched directly in its center was the cabin he&rsquo;d stayed in with his father the summer before. He turned around to see if Tim was still chasing him and saw that the boy was only a few feet behind him, still frantically sprinting with bloody spit flying from his crooked mouth. Mark reached the porch and ran up to the front door. It was unlocked! He flung it open, ran inside and jammed it back shut with the full weight of his small body. Moments later he felt a bang as Tim ran directly into the door. He subsequently heard a succession of thuds as the boy&rsquo;s body toppled backwards down the steps. He looked out the window and saw Tim lying motionless on the grass in front of the cabin. He quickly ran to the living room and pushed one of the chairs under the handle.</p>
                    <p>&nbsp; &nbsp;&nbsp;Panting, Mark began to edge away from the door as if he expected it to burst open at any minute, letting what was left of his friend inside. Shaking, he cautiously sat down at the little kitchen table without taking his eyes off of the entrance.&nbsp;</p>
                    <p>&nbsp; &nbsp;&nbsp;&ldquo;You&rsquo;re fine, you&rsquo;re fine, you&rsquo;re fine&hellip; There&rsquo;s food upstairs, you can just wait here. You can just wait until it&rsquo;s safe to leave. Then you can go get help and&hellip;&rdquo;</p>
                    <p>&nbsp; &nbsp;&nbsp;There was someone else sitting at the table. Mark didn&rsquo;t need to turn his head and meet the intruder&rsquo;s bloody grin to know this. The pain of the man&rsquo;s gaze boring into the back of his head was evidence enough. The intruder got up from the table and began a slow, methodical walk towards the door. He calmly dislodged the chair from the handle and moved it aside.&nbsp;</p>
                    <p>&nbsp; &nbsp;&nbsp;&ldquo;I&rsquo;m glad you&rsquo;ve come to join us, son.&rdquo; said his father. &ldquo;We&rsquo;ve missed you all alone in these woods. We&rsquo;ve been worried about you,&rdquo; he smiled.</p>
                    <p>&nbsp; &nbsp;&nbsp;Mark saw Tim&rsquo;s grinning face in the window and then watched as he opened the door and joined his father in the cabin.&nbsp;</p>
                    <p>&nbsp; &nbsp;&nbsp;&ldquo;Welcome home Mark,&rdquo; said his father as he reached out to place his contorted hand on Mark&rsquo;s shoulder.</p>
                    <p><br /></p>
                    <p style={{ textAlign: "center" }}>#</p>
                    <p>At that same moment, in a world that Mark no longer lived in, there was chaos. &ldquo;We&rsquo;re losing him!&rdquo; yelled the doctor standing beside Mark&rsquo;s crippled form in the hospital bed. He looked at the screeching monitor attached to the instruments around Mark&rsquo;s body. Instead of the steady stream of digital mountains and valleys he hoped to see, there was just a single horizontal line. The nurses handed him a defibrillator.&nbsp;</p>
                    <p>&ldquo;Clear!&rdquo; Mark&rsquo;s lifeless body jumped as electricity from the machine rushed through him. The doctor looked at the computer again, but to his dismay saw no change.&nbsp;</p>
                    <p>&nbsp; &nbsp;&nbsp;&ldquo;Full charge. Clear!&rdquo; The boy&rsquo;s body leaped for a second time but the line on the monitor remained obstinately flat. The doctor looked around the room and shook his head.&nbsp;</p>
                    <p>&nbsp; &nbsp; The tone was just as morbid when Mark was placed in the ground beside the other victims of the crash a week later. He was interred between his father and his best friend in the sunny little stretch of property they had been driving to for their camping trip.</p>
                </Typography>
            </div>
        </div>
    )
}

export default Camp;